# Generated by Django 5.1.2 on 2024-11-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_register_id_alter_register_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirm_password',
        ),
    ]
